### ISSUE TITLE
Assalomu alaykum! Ahrorbek shu projectni siz qilgan  section qismida, yozuvlar oldidan iconlari qolib ketgan, shuni to'g'irlab qo'ysak yaxshi bo'lar edi!👌

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [shakhbozbekusmonov/29-dars#10]
![image](https://user-images.githubusercontent.com/83509440/206682894-444db38f-0c7e-46c8-9faf-30bfc253f39e.png)

**Comment by shakhbozbekusmonov** [comment]
Ahrorbek xatoliklarni tuzatishga harakat qilibsiz juda hursandmiz, lekin rasmlar iconlar chiqmadi shuni ham tuzatib qo'ysak yaxshi bo'lar edi✔
![image](https://user-images.githubusercontent.com/83509440/206687443-6ca4f604-55f9-455a-8a6e-9701d0a74324.png)

**Comment by Ahror02** [comment]
okay . I loaded

**Comment by shakhbozbekusmonov** [comment]
Thanks!
