### ISSUE TITLE
Assalomu alaykum! Feruz shu projectni siz qilgan qismingiz bilan get ready qismi almashib qolgan, ya'ni siz qilgan section main ni ichida bo'lishi kerak va get readydan tepada turishi kerak, shuni to'g'irlab qo'ysak yaxshi bo'lar edi!😃

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [shakhbozbekusmonov/29-dars#11]
![image](https://user-images.githubusercontent.com/83509440/206683432-b817f1a8-988f-473f-b611-da1e5f29cc2b.png)

**Comment by shakhbozbekusmonov** [comment]
Feruz siz qilgan sectionda, yana bir necha xatoliklar mavjud shularni ko'rsatib o'tdim, shu xatoliklarni to'g'irlab qo'ysak yaxshi bo'lar edi!🚑
![image](https://user-images.githubusercontent.com/83509440/206683921-f8e0f752-046e-4d5e-b98b-3b16b44be7e6.png)

**Comment by feruzbekismoilov** [comment]
yorvordim ustoz

**Comment by shakhbozbekusmonov** [comment]
Juda ham yaxshi natijani ko'rdim! Barakalla✔
![image](https://user-images.githubusercontent.com/83509440/206685609-db59ae37-73f8-45d7-ac4d-ddb4b0e36b1e.png)
