### ISSUE TITLE
Assalomu alaykum! Do'stim Dostonjon, shu projectni siz qilgan footer qismida bir necha xatoliklar aniqlandi shularni ko'rsatib o'tdim, shu kamchiliklarni to'g'irlab qo'ysak yaxshi  bo'lar edi!🚑

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [shakhbozbekusmonov/29-dars#13]
![image](https://user-images.githubusercontent.com/83509440/206684507-7d560bb0-2613-4513-93a4-48f5445d2789.png)

**Comment by HomidovDoston** [comment]
asalomu aleykum ustoz ! xatolarni etganiz uchun raxmat , xatoni 5 min ichida yes qvordim!!! Thank you

**Comment by shakhbozbekusmonov** [comment]
Xatolarni juda ham yaxshi to'g'irlabsiz, gap yo'q!
![image](https://user-images.githubusercontent.com/83509440/206686439-8b7e0468-82bb-4ede-95a3-697fdcc74db1.png)

**Comment by HomidovDoston** [comment]
Raxmat xursand bo'ldim 🙂
